### ISSUE TITLE
Missing s in the repo name

### ISSUE THREAD

**Issue by SuperSandro2000** [arkane-systems/wsl-drop-cache#3]
All links and names in https://github.com/arkane-systems/wsl-transdebian/blob/master/apt/pool/main/w/wsl-drop-caches/wsl-drop-caches_0.4.dsc point to https://github.com/arkane-systems/wsl-drop-caches which results in a 404.

**Comment by cerebrate** [comment]
Fixed in 0.5 release, now out.
